package com.mainshell.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table MS_Words.
 */
@Entity(nameInDb = "MS_WORDS")
public class Word {
    @Id(autoincrement = true)
    @Property(nameInDb = "ID")
    private Long ID;

    @NotNull
    private int I_WID;

    private String S_WNAME;

    private String S_WVALUE;

    private String S_WVALUEEX;

    private String S_WGROUP;

    private Integer I_WPARENTID;
    
    private String S_WREMARK;

    @Generated(hash = 1055452772)
    public Word(Long ID, int I_WID, String S_WNAME, String S_WVALUE, String S_WVALUEEX,
            String S_WGROUP, Integer I_WPARENTID, String S_WREMARK) {
        this.ID = ID;
        this.I_WID = I_WID;
        this.S_WNAME = S_WNAME;
        this.S_WVALUE = S_WVALUE;
        this.S_WVALUEEX = S_WVALUEEX;
        this.S_WGROUP = S_WGROUP;
        this.I_WPARENTID = I_WPARENTID;
        this.S_WREMARK = S_WREMARK;
    }

    @Generated(hash = 3342184)
    public Word() {
    }

    public Long getID() {
        return this.ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public int getI_WID() {
        return this.I_WID;
    }

    public void setI_WID(int I_WID) {
        this.I_WID = I_WID;
    }

    public String getS_WNAME() {
        return this.S_WNAME;
    }

    public void setS_WNAME(String S_WNAME) {
        this.S_WNAME = S_WNAME;
    }

    public String getS_WVALUE() {
        return this.S_WVALUE;
    }

    public void setS_WVALUE(String S_WVALUE) {
        this.S_WVALUE = S_WVALUE;
    }

    public String getS_WVALUEEX() {
        return this.S_WVALUEEX;
    }

    public void setS_WVALUEEX(String S_WVALUEEX) {
        this.S_WVALUEEX = S_WVALUEEX;
    }

    public String getS_WGROUP() {
        return this.S_WGROUP;
    }

    public void setS_WGROUP(String S_WGROUP) {
        this.S_WGROUP = S_WGROUP;
    }

    public Integer getI_WPARENTID() {
        return this.I_WPARENTID;
    }

    public void setI_WPARENTID(Integer I_WPARENTID) {
        this.I_WPARENTID = I_WPARENTID;
    }

    public String getS_WREMARK() {
        return this.S_WREMARK;
    }

    public void setS_WREMARK(String S_WREMARK) {
        this.S_WREMARK = S_WREMARK;
    }

    

    
}
