package com.sh3h.localprovider.greendaoDao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        ArrearAgeDao.createTable(db, ifNotExists);
        ArrearAgeTotalDao.createTable(db, ifNotExists);
        CaliberDao.createTable(db, ifNotExists);
        CaliberRangeDao.createTable(db, ifNotExists);
        CardDao.createTable(db, ifNotExists);
        ChargeDao.createTable(db, ifNotExists);
        MeterModelDao.createTable(db, ifNotExists);
        MeterProducerDao.createTable(db, ifNotExists);
        MeterWorkerDao.createTable(db, ifNotExists);
        MultimediaDao.createTable(db, ifNotExists);
        PreviousRecordDao.createTable(db, ifNotExists);
        PriceDao.createTable(db, ifNotExists);
        PriceCategoryDao.createTable(db, ifNotExists);
        PriceDetailDao.createTable(db, ifNotExists);
        PriceitemDao.createTable(db, ifNotExists);
        ReadStateDao.createTable(db, ifNotExists);
        ReCordDao.createTable(db, ifNotExists);
        TaskDao.createTable(db, ifNotExists);
        WordDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        ArrearAgeDao.dropTable(db, ifExists);
        ArrearAgeTotalDao.dropTable(db, ifExists);
        CaliberDao.dropTable(db, ifExists);
        CaliberRangeDao.dropTable(db, ifExists);
        CardDao.dropTable(db, ifExists);
        ChargeDao.dropTable(db, ifExists);
        MeterModelDao.dropTable(db, ifExists);
        MeterProducerDao.dropTable(db, ifExists);
        MeterWorkerDao.dropTable(db, ifExists);
        MultimediaDao.dropTable(db, ifExists);
        PreviousRecordDao.dropTable(db, ifExists);
        PriceDao.dropTable(db, ifExists);
        PriceCategoryDao.dropTable(db, ifExists);
        PriceDetailDao.dropTable(db, ifExists);
        PriceitemDao.dropTable(db, ifExists);
        ReadStateDao.dropTable(db, ifExists);
        ReCordDao.dropTable(db, ifExists);
        TaskDao.dropTable(db, ifExists);
        WordDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ArrearAgeDao.class);
        registerDaoClass(ArrearAgeTotalDao.class);
        registerDaoClass(CaliberDao.class);
        registerDaoClass(CaliberRangeDao.class);
        registerDaoClass(CardDao.class);
        registerDaoClass(ChargeDao.class);
        registerDaoClass(MeterModelDao.class);
        registerDaoClass(MeterProducerDao.class);
        registerDaoClass(MeterWorkerDao.class);
        registerDaoClass(MultimediaDao.class);
        registerDaoClass(PreviousRecordDao.class);
        registerDaoClass(PriceDao.class);
        registerDaoClass(PriceCategoryDao.class);
        registerDaoClass(PriceDetailDao.class);
        registerDaoClass(PriceitemDao.class);
        registerDaoClass(ReadStateDao.class);
        registerDaoClass(ReCordDao.class);
        registerDaoClass(TaskDao.class);
        registerDaoClass(WordDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
