package com.sh3h.localprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.localprovider.greendaoEntity.MeterProducer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MR_METERPRODUCER".
*/
public class MeterProducerDao extends AbstractDao<MeterProducer, Long> {

    public static final String TABLENAME = "MR_METERPRODUCER";

    /**
     * Properties of entity MeterProducer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property PRODUCER_ID = new Property(1, String.class, "PRODUCER_ID", false, "PRODUCER__ID");
        public final static Property PRODUCER_NAME = new Property(2, int.class, "PRODUCER_NAME", false, "PRODUCER__NAME");
        public final static Property PRODUCER_REMARK = new Property(3, double.class, "PRODUCER_REMARK", false, "PRODUCER__REMARK");
    }


    public MeterProducerDao(DaoConfig config) {
        super(config);
    }
    
    public MeterProducerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MR_METERPRODUCER\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"PRODUCER__ID\" TEXT NOT NULL ," + // 1: PRODUCER_ID
                "\"PRODUCER__NAME\" INTEGER NOT NULL ," + // 2: PRODUCER_NAME
                "\"PRODUCER__REMARK\" REAL NOT NULL );"); // 3: PRODUCER_REMARK
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MR_METERPRODUCER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MeterProducer entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getPRODUCER_ID());
        stmt.bindLong(3, entity.getPRODUCER_NAME());
        stmt.bindDouble(4, entity.getPRODUCER_REMARK());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MeterProducer entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getPRODUCER_ID());
        stmt.bindLong(3, entity.getPRODUCER_NAME());
        stmt.bindDouble(4, entity.getPRODUCER_REMARK());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MeterProducer readEntity(Cursor cursor, int offset) {
        MeterProducer entity = new MeterProducer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getString(offset + 1), // PRODUCER_ID
            cursor.getInt(offset + 2), // PRODUCER_NAME
            cursor.getDouble(offset + 3) // PRODUCER_REMARK
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MeterProducer entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPRODUCER_ID(cursor.getString(offset + 1));
        entity.setPRODUCER_NAME(cursor.getInt(offset + 2));
        entity.setPRODUCER_REMARK(cursor.getDouble(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MeterProducer entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MeterProducer entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MeterProducer entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
