package com.sh3h.localprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.localprovider.greendaoEntity.PreviousRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MR_PREVIOUSRECORD".
*/
public class PreviousRecordDao extends AbstractDao<PreviousRecord, Long> {

    public static final String TABLENAME = "MR_PREVIOUSRECORD";

    /**
     * Properties of entity PreviousRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property RECORD_Id = new Property(1, int.class, "RECORD_Id", false, "RECORD__ID");
        public final static Property CARD_ID = new Property(2, String.class, "CARD_ID", false, "CARD__ID");
        public final static Property SUBCOM_CODE = new Property(3, String.class, "SUBCOM_CODE", false, "SUBCOM__CODE");
        public final static Property BOOK_ID = new Property(4, String.class, "BOOK_ID", false, "BOOK__ID");
        public final static Property BOOK_SORT_INDEX = new Property(5, int.class, "BOOK_SORT_INDEX", false, "BOOK__SORT__INDEX");
        public final static Property READING = new Property(6, int.class, "READING", false, "READING");
        public final static Property READING1 = new Property(7, int.class, "READING1", false, "READING1");
        public final static Property READ_STATE = new Property(8, int.class, "READ_STATE", false, "READ__STATE");
        public final static Property READ_STATE_CN = new Property(9, String.class, "READ_STATE_CN", false, "READ__STATE__CN");
        public final static Property BILLING_MONTH = new Property(10, int.class, "BILLING_MONTH", false, "BILLING__MONTH");
        public final static Property READ_DATE = new Property(11, long.class, "READ_DATE", false, "READ__DATE");
        public final static Property READ_YEAR = new Property(12, int.class, "READ_YEAR", false, "READ__YEAR");
        public final static Property READ_MONTH = new Property(13, int.class, "READ_MONTH", false, "READ__MONTH");
        public final static Property READ_TIMES = new Property(14, int.class, "READ_TIMES", false, "READ__TIMES");
        public final static Property METER_READER = new Property(15, int.class, "METER_READER", false, "METER__READER");
        public final static Property RECORD_ENTRY_USER = new Property(16, int.class, "RECORD_ENTRY_USER", false, "RECORD__ENTRY__USER");
        public final static Property RECORD_ENTRY_TIME = new Property(17, long.class, "RECORD_ENTRY_TIME", false, "RECORD__ENTRY__TIME");
        public final static Property RECORD_METHOD = new Property(18, int.class, "RECORD_METHOD", false, "RECORD__METHOD");
        public final static Property RECORD_TYPE = new Property(19, int.class, "RECORD_TYPE", false, "RECORD__TYPE");
        public final static Property READ_WATER = new Property(20, int.class, "READ_WATER", false, "READ__WATER");
        public final static Property AVG_READ_WATER3 = new Property(21, int.class, "AVG_READ_WATER3", false, "AVG__READ__WATER3");
        public final static Property AVG_READ_WATER6 = new Property(22, int.class, "AVG_READ_WATER6", false, "AVG__READ__WATER6");
        public final static Property AVG_READ_WATER12 = new Property(23, int.class, "AVG_READ_WATER12", false, "AVG__READ__WATER12");
        public final static Property RECORD_STATE_LGID = new Property(24, int.class, "RECORD_STATE_LGID", false, "RECORD__STATE__LGID");
        public final static Property RECORD_REASON_LGID = new Property(25, int.class, "RECORD_REASON_LGID", false, "RECORD__REASON__LGID");
        public final static Property REMARK = new Property(26, String.class, "REMARK", false, "REMARK");
        public final static Property READCORD_REASON_APPEN = new Property(27, int.class, "READCORD_REASON_APPEN", false, "READCORD__REASON__APPEN");
        public final static Property STATE = new Property(28, int.class, "STATE", false, "STATE");
        public final static Property BAR_CODE = new Property(29, String.class, "BAR_CODE", false, "BAR__CODE");
        public final static Property SEAL_NUMBER = new Property(30, String.class, "SEAL_NUMBER", false, "SEAL__NUMBER");
        public final static Property METER_TYPE = new Property(31, int.class, "METER_TYPE", false, "METER__TYPE");
        public final static Property MAIN_CARD_ID = new Property(32, String.class, "MAIN_CARD_ID", false, "MAIN__CARD__ID");
        public final static Property TERMINATE_READING = new Property(33, String.class, "TERMINATE_READING", false, "TERMINATE__READING");
        public final static Property INITIATE_READING = new Property(34, int.class, "INITIATE_READING", false, "INITIATE__READING");
        public final static Property CALIBER_ID = new Property(35, int.class, "CALIBER_ID", false, "CALIBER__ID");
        public final static Property METER_REPLACE_DATE = new Property(36, long.class, "METER_REPLACE_DATE", false, "METER__REPLACE__DATE");
        public final static Property METER_STATE = new Property(37, int.class, "METER_STATE", false, "METER__STATE");
        public final static Property ACC_WATER = new Property(38, int.class, "ACC_WATER", false, "ACC__WATER");
        public final static Property ACC_CHECK_MONEY = new Property(39, double.class, "ACC_CHECK_MONEY", false, "ACC__CHECK__MONEY");
        public final static Property LAST_READ_WATER = new Property(40, int.class, "LAST_READ_WATER", false, "LAST__READ__WATER");
        public final static Property LAST_READING = new Property(41, int.class, "LAST_READING", false, "LAST__READING");
        public final static Property LAST_READING1 = new Property(42, int.class, "LAST_READING1", false, "LAST__READING1");
        public final static Property LAST_READ_STATE = new Property(43, int.class, "LAST_READ_STATE", false, "LAST__READ__STATE");
        public final static Property LAST_READ_STATE_CN = new Property(44, String.class, "LAST_READ_STATE_CN", false, "LAST__READ__STATE__CN");
        public final static Property LAST_READ_DATE = new Property(45, long.class, "LAST_READ_DATE", false, "LAST__READ__DATE");
    }


    public PreviousRecordDao(DaoConfig config) {
        super(config);
    }
    
    public PreviousRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MR_PREVIOUSRECORD\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"RECORD__ID\" INTEGER NOT NULL ," + // 1: RECORD_Id
                "\"CARD__ID\" TEXT NOT NULL ," + // 2: CARD_ID
                "\"SUBCOM__CODE\" TEXT NOT NULL ," + // 3: SUBCOM_CODE
                "\"BOOK__ID\" TEXT NOT NULL ," + // 4: BOOK_ID
                "\"BOOK__SORT__INDEX\" INTEGER NOT NULL ," + // 5: BOOK_SORT_INDEX
                "\"READING\" INTEGER NOT NULL ," + // 6: READING
                "\"READING1\" INTEGER NOT NULL ," + // 7: READING1
                "\"READ__STATE\" INTEGER NOT NULL ," + // 8: READ_STATE
                "\"READ__STATE__CN\" TEXT NOT NULL ," + // 9: READ_STATE_CN
                "\"BILLING__MONTH\" INTEGER NOT NULL ," + // 10: BILLING_MONTH
                "\"READ__DATE\" INTEGER NOT NULL ," + // 11: READ_DATE
                "\"READ__YEAR\" INTEGER NOT NULL ," + // 12: READ_YEAR
                "\"READ__MONTH\" INTEGER NOT NULL ," + // 13: READ_MONTH
                "\"READ__TIMES\" INTEGER NOT NULL ," + // 14: READ_TIMES
                "\"METER__READER\" INTEGER NOT NULL ," + // 15: METER_READER
                "\"RECORD__ENTRY__USER\" INTEGER NOT NULL ," + // 16: RECORD_ENTRY_USER
                "\"RECORD__ENTRY__TIME\" INTEGER NOT NULL ," + // 17: RECORD_ENTRY_TIME
                "\"RECORD__METHOD\" INTEGER NOT NULL ," + // 18: RECORD_METHOD
                "\"RECORD__TYPE\" INTEGER NOT NULL ," + // 19: RECORD_TYPE
                "\"READ__WATER\" INTEGER NOT NULL ," + // 20: READ_WATER
                "\"AVG__READ__WATER3\" INTEGER NOT NULL ," + // 21: AVG_READ_WATER3
                "\"AVG__READ__WATER6\" INTEGER NOT NULL ," + // 22: AVG_READ_WATER6
                "\"AVG__READ__WATER12\" INTEGER NOT NULL ," + // 23: AVG_READ_WATER12
                "\"RECORD__STATE__LGID\" INTEGER NOT NULL ," + // 24: RECORD_STATE_LGID
                "\"RECORD__REASON__LGID\" INTEGER NOT NULL ," + // 25: RECORD_REASON_LGID
                "\"REMARK\" TEXT," + // 26: REMARK
                "\"READCORD__REASON__APPEN\" INTEGER NOT NULL ," + // 27: READCORD_REASON_APPEN
                "\"STATE\" INTEGER NOT NULL ," + // 28: STATE
                "\"BAR__CODE\" TEXT NOT NULL ," + // 29: BAR_CODE
                "\"SEAL__NUMBER\" TEXT NOT NULL ," + // 30: SEAL_NUMBER
                "\"METER__TYPE\" INTEGER NOT NULL ," + // 31: METER_TYPE
                "\"MAIN__CARD__ID\" TEXT," + // 32: MAIN_CARD_ID
                "\"TERMINATE__READING\" TEXT NOT NULL ," + // 33: TERMINATE_READING
                "\"INITIATE__READING\" INTEGER NOT NULL ," + // 34: INITIATE_READING
                "\"CALIBER__ID\" INTEGER NOT NULL ," + // 35: CALIBER_ID
                "\"METER__REPLACE__DATE\" INTEGER NOT NULL ," + // 36: METER_REPLACE_DATE
                "\"METER__STATE\" INTEGER NOT NULL ," + // 37: METER_STATE
                "\"ACC__WATER\" INTEGER NOT NULL ," + // 38: ACC_WATER
                "\"ACC__CHECK__MONEY\" REAL NOT NULL ," + // 39: ACC_CHECK_MONEY
                "\"LAST__READ__WATER\" INTEGER NOT NULL ," + // 40: LAST_READ_WATER
                "\"LAST__READING\" INTEGER NOT NULL ," + // 41: LAST_READING
                "\"LAST__READING1\" INTEGER NOT NULL ," + // 42: LAST_READING1
                "\"LAST__READ__STATE\" INTEGER NOT NULL ," + // 43: LAST_READ_STATE
                "\"LAST__READ__STATE__CN\" TEXT NOT NULL ," + // 44: LAST_READ_STATE_CN
                "\"LAST__READ__DATE\" INTEGER NOT NULL );"); // 45: LAST_READ_DATE
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MR_PREVIOUSRECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PreviousRecord entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getRECORD_Id());
        stmt.bindString(3, entity.getCARD_ID());
        stmt.bindString(4, entity.getSUBCOM_CODE());
        stmt.bindString(5, entity.getBOOK_ID());
        stmt.bindLong(6, entity.getBOOK_SORT_INDEX());
        stmt.bindLong(7, entity.getREADING());
        stmt.bindLong(8, entity.getREADING1());
        stmt.bindLong(9, entity.getREAD_STATE());
        stmt.bindString(10, entity.getREAD_STATE_CN());
        stmt.bindLong(11, entity.getBILLING_MONTH());
        stmt.bindLong(12, entity.getREAD_DATE());
        stmt.bindLong(13, entity.getREAD_YEAR());
        stmt.bindLong(14, entity.getREAD_MONTH());
        stmt.bindLong(15, entity.getREAD_TIMES());
        stmt.bindLong(16, entity.getMETER_READER());
        stmt.bindLong(17, entity.getRECORD_ENTRY_USER());
        stmt.bindLong(18, entity.getRECORD_ENTRY_TIME());
        stmt.bindLong(19, entity.getRECORD_METHOD());
        stmt.bindLong(20, entity.getRECORD_TYPE());
        stmt.bindLong(21, entity.getREAD_WATER());
        stmt.bindLong(22, entity.getAVG_READ_WATER3());
        stmt.bindLong(23, entity.getAVG_READ_WATER6());
        stmt.bindLong(24, entity.getAVG_READ_WATER12());
        stmt.bindLong(25, entity.getRECORD_STATE_LGID());
        stmt.bindLong(26, entity.getRECORD_REASON_LGID());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(27, REMARK);
        }
        stmt.bindLong(28, entity.getREADCORD_REASON_APPEN());
        stmt.bindLong(29, entity.getSTATE());
        stmt.bindString(30, entity.getBAR_CODE());
        stmt.bindString(31, entity.getSEAL_NUMBER());
        stmt.bindLong(32, entity.getMETER_TYPE());
 
        String MAIN_CARD_ID = entity.getMAIN_CARD_ID();
        if (MAIN_CARD_ID != null) {
            stmt.bindString(33, MAIN_CARD_ID);
        }
        stmt.bindString(34, entity.getTERMINATE_READING());
        stmt.bindLong(35, entity.getINITIATE_READING());
        stmt.bindLong(36, entity.getCALIBER_ID());
        stmt.bindLong(37, entity.getMETER_REPLACE_DATE());
        stmt.bindLong(38, entity.getMETER_STATE());
        stmt.bindLong(39, entity.getACC_WATER());
        stmt.bindDouble(40, entity.getACC_CHECK_MONEY());
        stmt.bindLong(41, entity.getLAST_READ_WATER());
        stmt.bindLong(42, entity.getLAST_READING());
        stmt.bindLong(43, entity.getLAST_READING1());
        stmt.bindLong(44, entity.getLAST_READ_STATE());
        stmt.bindString(45, entity.getLAST_READ_STATE_CN());
        stmt.bindLong(46, entity.getLAST_READ_DATE());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PreviousRecord entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getRECORD_Id());
        stmt.bindString(3, entity.getCARD_ID());
        stmt.bindString(4, entity.getSUBCOM_CODE());
        stmt.bindString(5, entity.getBOOK_ID());
        stmt.bindLong(6, entity.getBOOK_SORT_INDEX());
        stmt.bindLong(7, entity.getREADING());
        stmt.bindLong(8, entity.getREADING1());
        stmt.bindLong(9, entity.getREAD_STATE());
        stmt.bindString(10, entity.getREAD_STATE_CN());
        stmt.bindLong(11, entity.getBILLING_MONTH());
        stmt.bindLong(12, entity.getREAD_DATE());
        stmt.bindLong(13, entity.getREAD_YEAR());
        stmt.bindLong(14, entity.getREAD_MONTH());
        stmt.bindLong(15, entity.getREAD_TIMES());
        stmt.bindLong(16, entity.getMETER_READER());
        stmt.bindLong(17, entity.getRECORD_ENTRY_USER());
        stmt.bindLong(18, entity.getRECORD_ENTRY_TIME());
        stmt.bindLong(19, entity.getRECORD_METHOD());
        stmt.bindLong(20, entity.getRECORD_TYPE());
        stmt.bindLong(21, entity.getREAD_WATER());
        stmt.bindLong(22, entity.getAVG_READ_WATER3());
        stmt.bindLong(23, entity.getAVG_READ_WATER6());
        stmt.bindLong(24, entity.getAVG_READ_WATER12());
        stmt.bindLong(25, entity.getRECORD_STATE_LGID());
        stmt.bindLong(26, entity.getRECORD_REASON_LGID());
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(27, REMARK);
        }
        stmt.bindLong(28, entity.getREADCORD_REASON_APPEN());
        stmt.bindLong(29, entity.getSTATE());
        stmt.bindString(30, entity.getBAR_CODE());
        stmt.bindString(31, entity.getSEAL_NUMBER());
        stmt.bindLong(32, entity.getMETER_TYPE());
 
        String MAIN_CARD_ID = entity.getMAIN_CARD_ID();
        if (MAIN_CARD_ID != null) {
            stmt.bindString(33, MAIN_CARD_ID);
        }
        stmt.bindString(34, entity.getTERMINATE_READING());
        stmt.bindLong(35, entity.getINITIATE_READING());
        stmt.bindLong(36, entity.getCALIBER_ID());
        stmt.bindLong(37, entity.getMETER_REPLACE_DATE());
        stmt.bindLong(38, entity.getMETER_STATE());
        stmt.bindLong(39, entity.getACC_WATER());
        stmt.bindDouble(40, entity.getACC_CHECK_MONEY());
        stmt.bindLong(41, entity.getLAST_READ_WATER());
        stmt.bindLong(42, entity.getLAST_READING());
        stmt.bindLong(43, entity.getLAST_READING1());
        stmt.bindLong(44, entity.getLAST_READ_STATE());
        stmt.bindString(45, entity.getLAST_READ_STATE_CN());
        stmt.bindLong(46, entity.getLAST_READ_DATE());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PreviousRecord readEntity(Cursor cursor, int offset) {
        PreviousRecord entity = new PreviousRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getInt(offset + 1), // RECORD_Id
            cursor.getString(offset + 2), // CARD_ID
            cursor.getString(offset + 3), // SUBCOM_CODE
            cursor.getString(offset + 4), // BOOK_ID
            cursor.getInt(offset + 5), // BOOK_SORT_INDEX
            cursor.getInt(offset + 6), // READING
            cursor.getInt(offset + 7), // READING1
            cursor.getInt(offset + 8), // READ_STATE
            cursor.getString(offset + 9), // READ_STATE_CN
            cursor.getInt(offset + 10), // BILLING_MONTH
            cursor.getLong(offset + 11), // READ_DATE
            cursor.getInt(offset + 12), // READ_YEAR
            cursor.getInt(offset + 13), // READ_MONTH
            cursor.getInt(offset + 14), // READ_TIMES
            cursor.getInt(offset + 15), // METER_READER
            cursor.getInt(offset + 16), // RECORD_ENTRY_USER
            cursor.getLong(offset + 17), // RECORD_ENTRY_TIME
            cursor.getInt(offset + 18), // RECORD_METHOD
            cursor.getInt(offset + 19), // RECORD_TYPE
            cursor.getInt(offset + 20), // READ_WATER
            cursor.getInt(offset + 21), // AVG_READ_WATER3
            cursor.getInt(offset + 22), // AVG_READ_WATER6
            cursor.getInt(offset + 23), // AVG_READ_WATER12
            cursor.getInt(offset + 24), // RECORD_STATE_LGID
            cursor.getInt(offset + 25), // RECORD_REASON_LGID
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // REMARK
            cursor.getInt(offset + 27), // READCORD_REASON_APPEN
            cursor.getInt(offset + 28), // STATE
            cursor.getString(offset + 29), // BAR_CODE
            cursor.getString(offset + 30), // SEAL_NUMBER
            cursor.getInt(offset + 31), // METER_TYPE
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // MAIN_CARD_ID
            cursor.getString(offset + 33), // TERMINATE_READING
            cursor.getInt(offset + 34), // INITIATE_READING
            cursor.getInt(offset + 35), // CALIBER_ID
            cursor.getLong(offset + 36), // METER_REPLACE_DATE
            cursor.getInt(offset + 37), // METER_STATE
            cursor.getInt(offset + 38), // ACC_WATER
            cursor.getDouble(offset + 39), // ACC_CHECK_MONEY
            cursor.getInt(offset + 40), // LAST_READ_WATER
            cursor.getInt(offset + 41), // LAST_READING
            cursor.getInt(offset + 42), // LAST_READING1
            cursor.getInt(offset + 43), // LAST_READ_STATE
            cursor.getString(offset + 44), // LAST_READ_STATE_CN
            cursor.getLong(offset + 45) // LAST_READ_DATE
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PreviousRecord entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRECORD_Id(cursor.getInt(offset + 1));
        entity.setCARD_ID(cursor.getString(offset + 2));
        entity.setSUBCOM_CODE(cursor.getString(offset + 3));
        entity.setBOOK_ID(cursor.getString(offset + 4));
        entity.setBOOK_SORT_INDEX(cursor.getInt(offset + 5));
        entity.setREADING(cursor.getInt(offset + 6));
        entity.setREADING1(cursor.getInt(offset + 7));
        entity.setREAD_STATE(cursor.getInt(offset + 8));
        entity.setREAD_STATE_CN(cursor.getString(offset + 9));
        entity.setBILLING_MONTH(cursor.getInt(offset + 10));
        entity.setREAD_DATE(cursor.getLong(offset + 11));
        entity.setREAD_YEAR(cursor.getInt(offset + 12));
        entity.setREAD_MONTH(cursor.getInt(offset + 13));
        entity.setREAD_TIMES(cursor.getInt(offset + 14));
        entity.setMETER_READER(cursor.getInt(offset + 15));
        entity.setRECORD_ENTRY_USER(cursor.getInt(offset + 16));
        entity.setRECORD_ENTRY_TIME(cursor.getLong(offset + 17));
        entity.setRECORD_METHOD(cursor.getInt(offset + 18));
        entity.setRECORD_TYPE(cursor.getInt(offset + 19));
        entity.setREAD_WATER(cursor.getInt(offset + 20));
        entity.setAVG_READ_WATER3(cursor.getInt(offset + 21));
        entity.setAVG_READ_WATER6(cursor.getInt(offset + 22));
        entity.setAVG_READ_WATER12(cursor.getInt(offset + 23));
        entity.setRECORD_STATE_LGID(cursor.getInt(offset + 24));
        entity.setRECORD_REASON_LGID(cursor.getInt(offset + 25));
        entity.setREMARK(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setREADCORD_REASON_APPEN(cursor.getInt(offset + 27));
        entity.setSTATE(cursor.getInt(offset + 28));
        entity.setBAR_CODE(cursor.getString(offset + 29));
        entity.setSEAL_NUMBER(cursor.getString(offset + 30));
        entity.setMETER_TYPE(cursor.getInt(offset + 31));
        entity.setMAIN_CARD_ID(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setTERMINATE_READING(cursor.getString(offset + 33));
        entity.setINITIATE_READING(cursor.getInt(offset + 34));
        entity.setCALIBER_ID(cursor.getInt(offset + 35));
        entity.setMETER_REPLACE_DATE(cursor.getLong(offset + 36));
        entity.setMETER_STATE(cursor.getInt(offset + 37));
        entity.setACC_WATER(cursor.getInt(offset + 38));
        entity.setACC_CHECK_MONEY(cursor.getDouble(offset + 39));
        entity.setLAST_READ_WATER(cursor.getInt(offset + 40));
        entity.setLAST_READING(cursor.getInt(offset + 41));
        entity.setLAST_READING1(cursor.getInt(offset + 42));
        entity.setLAST_READ_STATE(cursor.getInt(offset + 43));
        entity.setLAST_READ_STATE_CN(cursor.getString(offset + 44));
        entity.setLAST_READ_DATE(cursor.getLong(offset + 45));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PreviousRecord entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PreviousRecord entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PreviousRecord entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
